### ISSUE TITLE
win10环境有bug

### ISSUE THREAD

**Issue by TAYUN** [houdunwang/camera#2]
试了下，win10系统，从1080分辨率的拓展屏幕移到2k分辨率屏幕会断触、卡顿、慢慢放大的，然后鼠标碰到项目窗口不受控抖动bug。

**Comment by houdunwang** [comment]
我下个版本修复这个问题

**Comment by houdunwang** [comment]
如果你是程序员，你也可以修复，然后提 PR，这样就好了，我省些事，哈。。谢谢你发现的问题

**Comment by houdunwang** [comment]
问题已经修复完了，关闭了
