### ISSUE TITLE
BUG：窗口拖动的若干问题

### ISSUE THREAD

**Issue by orangelckc** [houdunwang/camera#4]
1. 鼠标拖动窗口过快时，窗口不跟手，卡顿
2. 窗口内部点击右键后，移出窗口，在窗口外部点击左键，移回窗口后即可无需点击拖动窗口
![屏幕录制2023-03-06 21 53 07](https://user-images.githubusercontent.com/48410934/223228714-2189d5f3-9c4b-4e92-a095-1a4ee6890816.gif)

平台：macOS 12.6.1

**Comment by houdunwang** [comment]
谢谢反馈的问题，这个问题我也发现了，但没有你这么卡顿，我解决一下

**Comment by houdunwang** [comment]
问题已经修复完毕了
