### ISSUE TITLE
切换到圆形界面时，在摄像头页面，鼠标在悬浮下拉菜单时，会很明显的看到下面工具栏闪成长方形，再变成圆形。

### ISSUE THREAD

**Issue by miaopass-future** [houdunwang/camera#6]
如题所示。
切换到圆形界面时，在摄像头页面，鼠标在悬浮下拉菜单（第四个汉堡包图标）时（在弹出下拉菜单的一瞬间），会很明显的看到下面工具栏闪成长方形，再变成圆形。

环境;windows 10

只是一瞬间的变化，无法截图，不知道能不能做成比较自然的过渡。

**Comment by houdunwang** [comment]
感谢你发现的反馈，我平时使用window较少，我测试一下，然后修复这个问题，问题已经收录

**Comment by houdunwang** [comment]
这个问题，我后面找时间处理一下
