### ISSUE TITLE
圆形时画面会溢出

### ISSUE THREAD

**Issue by phoben** [houdunwang/camera#9]
大叔，windows版本，圆形时画面会溢出呢。
![image](https://github.com/houdunwang/camera/assets/55103351/ba9d33ab-151a-4e79-b605-c3ec92890219)

**Comment by houdunwang** [comment]
有人反应过这个问题，可能是 windows 系统版本比较低，我手里没有低版本的 win 等哪天我虚拟机搞一个测试一下，这是小问题。谢谢反馈，我就先关了  新年快乐
